
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class AchPaymentMethod
    {

        [SerializeField]
        [JsonProperty("bankName")]
        public string? BankName { get; set; }

        [SerializeField]
        [JsonProperty("last4")]
        public string? Last4 { get; set; }
    }
}