
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using HathoraCloud.Models.Shared;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ApplicationWithLatestDeploymentAndBuildDeprecatedDeployment
    {

        /// <summary>
        /// Additional ports your server listens on.
        /// </summary>
        [SerializeField]
        [JsonProperty("additionalContainerPorts")]
        public List<ContainerPort> AdditionalContainerPorts { get; set; } = default!;

        /// <summary>
        /// System generated unique identifier for an application.
        /// </summary>
        [SerializeField]
        [JsonProperty("appId")]
        public string AppId { get; set; } = default!;

        /// <summary>
        /// A build represents a game server artifact and its associated metadata.
        /// </summary>
        [SerializeField]
        [JsonProperty("build")]
        public Build Build { get; set; } = default!;

        /// <summary>
        /// System generated id for a build. Increments by 1.
        /// </summary>
        [SerializeField]
        [JsonProperty("buildId")]
        public int BuildId { get; set; } = default!;

        /// <summary>
        /// When the deployment was created.
        /// </summary>
        [SerializeField]
        [JsonProperty("createdAt")]
        public DateTime CreatedAt { get; set; } = default!;

        [SerializeField]
        [JsonProperty("createdBy")]
        public string CreatedBy { get; set; } = default!;

        /// <summary>
        /// A container port object represents the transport configruations for how your server will listen.
        /// </summary>
        [SerializeField]
        [JsonProperty("defaultContainerPort")]
        public ContainerPort DefaultContainerPort { get; set; } = default!;

        /// <summary>
        /// System generated id for a deployment. Increments by 1.
        /// </summary>
        [SerializeField]
        [JsonProperty("deploymentId")]
        public int DeploymentId { get; set; } = default!;

        /// <summary>
        /// The environment variable that our process will have access to at runtime.
        /// </summary>
        [SerializeField]
        [JsonProperty("env")]
        public List<ApplicationWithLatestDeploymentAndBuildDeprecatedEnv> Env { get; set; } = default!;

        /// <summary>
        /// Option to shut down processes that have had no new connections or rooms<br/>
        /// 
        /// <remarks>
        /// for five minutes.
        /// </remarks>
        /// </summary>
        [SerializeField]
        [JsonProperty("idleTimeoutEnabled")]
        public bool IdleTimeoutEnabled { get; set; } = default!;

        /// <summary>
        /// The number of cores allocated to your process.
        /// </summary>
        [SerializeField]
        [JsonProperty("requestedCPU")]
        public double RequestedCPU { get; set; } = default!;

        /// <summary>
        /// The amount of memory allocated to your process.
        /// </summary>
        [SerializeField]
        [JsonProperty("requestedMemoryMB")]
        public double RequestedMemoryMB { get; set; } = default!;

        /// <summary>
        /// Governs how many <a href="https://hathora.dev/docs/concepts/hathora-entities#room">rooms</a> can be scheduled in a process.
        /// </summary>
        [SerializeField]
        [JsonProperty("roomsPerProcess")]
        public int RoomsPerProcess { get; set; } = default!;
    }
}