
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class BuildPart
    {

        [SerializeField]
        [JsonProperty("partNumber")]
        public double PartNumber { get; set; } = default!;

        [SerializeField]
        [JsonProperty("putRequestUrl")]
        public string PutRequestUrl { get; set; } = default!;
    }
}