
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class InvoiceItem
    {

        [SerializeField]
        [JsonProperty("amount")]
        public double Amount { get; set; } = default!;

        [SerializeField]
        [JsonProperty("productName")]
        public string ProductName { get; set; } = default!;

        [SerializeField]
        [JsonProperty("quantity")]
        public double Quantity { get; set; } = default!;

        [SerializeField]
        [JsonProperty("unit")]
        public string Unit { get; set; } = default!;

        [SerializeField]
        [JsonProperty("unitPrice")]
        public double UnitPrice { get; set; } = default!;
    }
}