
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    public enum Region
    {
        [JsonProperty("Seattle")]
        Seattle,
        [JsonProperty("Los_Angeles")]
        LosAngeles,
        [JsonProperty("Washington_DC")]
        WashingtonDC,
        [JsonProperty("Chicago")]
        Chicago,
        [JsonProperty("London")]
        London,
        [JsonProperty("Frankfurt")]
        Frankfurt,
        [JsonProperty("Mumbai")]
        Mumbai,
        [JsonProperty("Singapore")]
        Singapore,
        [JsonProperty("Tokyo")]
        Tokyo,
        [JsonProperty("Sydney")]
        Sydney,
        [JsonProperty("Sao_Paulo")]
        SaoPaulo,
        [JsonProperty("Dallas")]
        Dallas,
    }

    public static class RegionExtension
    {
        public static string Value(this Region value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static Region ToEnum(this string value)
        {
            foreach(var field in typeof(Region).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    return (Region)field.GetValue(null);
                }
            }

            throw new Exception($"Unknown value {value} for enum Region");
        }
    }

}