
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class RegionalContainerTags
    {

        [SerializeField]
        [JsonProperty("containerTag")]
        public string ContainerTag { get; set; } = default!;
        

        [SerializeField]
        [JsonProperty("region")]
        public Region Region { get; set; } = default!;
        
    }
}