
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace HathoraCloud.Models.Shared
{
    using Newtonsoft.Json;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class SetLobbyStateParams
    {

        /// <summary>
        /// JSON blob to store metadata for a room. Must be smaller than 1MB.
        /// </summary>
        [SerializeField]
        [JsonProperty("state")]
        public object State { get; set; } = default!;
    }
}